dev:
  app_function: intelligibill.app
  aws_region: ap-southeast-2
  profile_name: default
  project_name: intelligibill
  runtime: python3.6
  s3_bucket: intelligibill-dev
  domain: dev.beatyourbill.com.au
  log_level: ERROR
  certificate_arn: arn:aws:acm:us-east-1:825327973641:certificate/14fc8b5c-1e40-44ce-9617-f531e5c2ce82
  authorizer:
    type: COGNITO_USER_POOLS
    provider_arns:
    - arn:aws:cognito-idp:ap-southeast-2:825327973641:userpool/ap-southeast-2_IG69RgQQJ
  context_header_mappings:
    user_id: authorizer.claims.sub
  iam_authorizer: yes
  cors: yes
  environment_variables:
    users_paid_table: paid_users
    users_bill_table: bill_users
    bests_offers_table: bests_offers
    upload_table: upload_free
    bills-bucket: myswitch-bills-bucket
    stripe.api_key: stripe_dev_key
    coupon: "BYB_TRIAL"
    source-bill: IB
    switch-bucket: switch-markintell
    feedback_list : contact@ag-study.com

free:
  app_function: free-intelligibill.app
  aws_region: ap-southeast-2
  profile_name: default
  project_name: intelligibill
  runtime: python3.6
  s3_bucket: intelligibill-dev
  domain: free.beatyourbill.com.au
  log_level: ERROR
  certificate_arn: arn:aws:acm:us-east-1:825327973641:certificate/14fc8b5c-1e40-44ce-9617-f531e5c2ce82
  cors: yes
  environment_variables:
    users_bill_table: bill_users
    bests_offers_table: bests_offers
    users_paid_table: paid_users
    upload_table: upload_free
    bills-bucket: myswitch-bills-bucket
    switch-bucket: switch-markintell
    feedback_list: contact@ag-study.com
    source-bill: IB

prodfree:
  app_function: free-intelligibill.app
  aws_region: ap-southeast-2
  profile_name: default
  project_name: intelligibill
  runtime: python3.6
  s3_bucket: intelligibill-dev
  domain: prodfree.beatyourbill.com.au
  log_level: ERROR
  certificate_arn: arn:aws:acm:us-east-1:825327973641:certificate/14fc8b5c-1e40-44ce-9617-f531e5c2ce82
  cors: yes
  environment_variables:
    users_bill_table: bill_users_prod
    bests_offers_table: bests_offers_prod
    upload_table: upload_prod_free
    users_paid_table: paid_users_prod
    bills-bucket: beatyourbill-bucket
    switch-bucket: byb-markintell
    source-bill: BYB
    feedback_list: contact@ag-study.com
  events:
  - function: byb_email.feeder.process_new_email
    event_source:
      arn: arn:aws:s3:::byb-emails
      events:
      - s3:ObjectCreated:*

api:
  app_function: intelligibill.app
  aws_region: ap-southeast-2
  profile_name: default
  project_name: intelligibill
  runtime: python3.6
  s3_bucket: intelligibill-api
  domain: api.beatyourbill.com.au
  log_level: ERROR
  certificate_arn: arn:aws:acm:us-east-1:825327973641:certificate/14fc8b5c-1e40-44ce-9617-f531e5c2ce82
  authorizer:
    type: COGNITO_USER_POOLS
    provider_arns:
    - arn:aws:cognito-idp:ap-southeast-2:825327973641:userpool/ap-southeast-2_IG69RgQQJ
  context_header_mappings:
    user_id: authorizer.claims.sub
  iam_authorizer: yes
  cors: yes
  environment_variables:
    users_paid_table: paid_users_prod
    users_bill_table: bill_users_prod
    bests_offers_table: bests_offers_prod
    upload_table: upload_prod_free
    bills-bucket: beatyourbill-bucket
    stripe.api_key: stripe_key
    coupon: "VOYANCE2020"
    source-bill: BYB
    switch-bucket: byb-markintell
    feedback_list : contact@ag-study.com, bruce.mountain@cmeaustralia.com.au